id = "overrideConstant";
title = "Override Attribute on Constant";
description = "";
code = "<?php

interface Shape {
    const SIDES = 0;
}

class Square implements Shape {
    #[\Override]
    const SIDES = 4; // Fine, overrides Shape::SIDES

    #[\Override]
    const COLOR = 'blue'; // Fatal error, no matching parent constant
}

enum eSquare implements Shape {
    #[\Override]
    const SIDES = 4; // Fine, overrides Shape::SIDES

    #[\Override]
    const COLOR = 'blue'; // Fatal error, no matching parent constant
}

?>";
before = "PHP Fatal error:  Attribute \"Override\" cannot target class constant (allowed targets: method)

Fatal error: Attribute \"Override\" cannot target class constant (allowed targets: method)
";
after = "";
seeAlso[] = "";
deprecation = "";
phpVersion = "8.5";
alternatives[] = "";
related[] = "";
keywords[] = "";
features[] = "";
phpError[] = "";